Install needed MatLab toolbox addons
Signed-off-by: James Noss <jnoss@jhu.edu>

diff --git a/docker/Dockerfile.olaf b/docker/Dockerfile.olaf
--- a/docker/Dockerfile.olaf
+++ b/docker/Dockerfile.olaf
@@ -1,4 +1,59 @@
-FROM mathworks/matlab:latest
+
+#-----This section was copied from https://github.com/mathworks-ref-arch/matlab-dockerfile/blob/main/alternates/building-on-matlab-docker-image/Dockerfile-----
+
+# To specify which MATLAB release to install in the container, edit the value of the MATLAB_RELEASE argument.
+# Use uppercase to specify the release, for example: ARG MATLAB_RELEASE=R2021b
+ARG MATLAB_RELEASE=R2024b
+
+# Specify the extra products to install into the image. These products can either be toolboxes or support packages.
+ARG ADDITIONAL_PRODUCTS="Image_Processing_Toolbox Navigation_Toolbox"
+
+FROM mathworks/matlab:$MATLAB_RELEASE
+
+# Declare the global argument to use at the current build stage
+ARG MATLAB_RELEASE
+ARG ADDITIONAL_PRODUCTS
+
+
+# By default, the MATLAB container runs as user "matlab". To install mpm dependencies, switch to root.
+USER root
+
+#RUN sudo apt-get update
+
+# Install mpm dependencies
+# Install mpm dependencies
+RUN export DEBIAN_FRONTEND=noninteractive \
+    && apt-get update \
+    && apt-get install --no-install-recommends --yes \
+        wget \
+        ca-certificates \
+    && apt-get clean \
+    && apt-get autoremove \
+    && rm -rf /var/lib/apt/lists/*
+
+# Run mpm to install MathWorks products into the existing MATLAB installation directory,
+# and delete the mpm installation afterwards.
+# Modify it by setting the ADDITIONAL_PRODUCTS defined above,
+# e.g. ADDITIONAL_PRODUCTS="Statistics_and_Machine_Learning_Toolbox Parallel_Computing_Toolbox MATLAB_Coder".
+# If mpm fails to install successfully then output the logfile to the terminal, otherwise cleanup.
+
+# Switch to user matlab, and pass in $HOME variable to mpm,
+# so that mpm can set the correct root folder for the support packages.
+WORKDIR /tmp
+USER matlab
+RUN wget -q https://www.mathworks.com/mpm/glnxa64/mpm \
+    && chmod +x mpm \
+    && EXISTING_MATLAB_LOCATION=$(dirname $(dirname $(readlink -f $(which matlab)))) \
+    && sudo HOME=${HOME} ./mpm install \
+        --destination=${EXISTING_MATLAB_LOCATION} \
+        --release=${MATLAB_RELEASE} \
+        --products ${ADDITIONAL_PRODUCTS} \
+    || (echo "MPM Installation Failure. See below for more information:" && cat /tmp/mathworks_root.log && false) \
+    && sudo rm -rf mpm /tmp/mathworks_root.log
+
+#-----End copy from https://github.com/mathworks-ref-arch/matlab-dockerfile/blob/main/alternates/building-on-matlab-docker-image/Dockerfile-----
+
+USER root
 
 # The matlab image leaves you in /home/matlab/Documents/MATLAB/
 WORKDIR ../../../../
@@ -6,6 +61,9 @@ WORKDIR ../../../../
 # install git
 RUN sudo apt-get update
 RUN sudo apt install git -y
+
+# Install vim for file editing.
+RUN sudo apt-get install -y vim
 
 # clone olaf ver v3.0
 WORKDIR /src
@@ -21,3 +79,4 @@ COPY data/ /data
 ENV MLM_LICENSE_FILE /sciserver/vc_crypt/ssec/jnoss/MLM_LICENSE_FILE
 
 #CMD ["matlab", "-nodisplay", "-nosplash", "-nodesktop", "-r", '"run('/src/olaf/Code/internal/mainFLFM.m'); exit;"']
+#matlab -nodisplay -nosplash -nodesktop -r "run('/src/olaf/Code/internal/mainFLFM.m'); exit;"
